name: Bug Report
description: Report a bug
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this issue. Please provide as much detail as possible.

  - type: input
    id: version
    attributes:
      label: Version
      description: "@zhiaiwan/utils version"
      placeholder: "0.0.1"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Problem Description
      description: Clearly and concisely describe the issue
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide minimal reproduction steps
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: Describe what actually happened

  - type: textarea
    id: context
    attributes:
      label: Environment
      description: "Node version, browser, OS, etc."
      render: text
