name: Feature Request
description: Suggest a new feature
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Clearly describe the feature you would like to add
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Use Case
      description: Why is this feature needed? What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Approach
      description: If you have implementation ideas, describe them here

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Have you considered any alternative solutions?
