import { toIterateeCore } from "./internal/iteratee-core.js";
import type { Iteratee } from "./types.js";

const identity = <TValue>(value: TValue): TValue => value;

/**
 * Creates an object with keys generated by running each own enumerable property of `object`
 * through `iteratee`. The corresponding value is the original property value.
 *
 * @since +0.1.0
 * @category Object
 * @param {Record<string, TValue> | null | undefined} object The object to iterate over.
 * @param {Iteratee<TValue, unknown>} [iteratee] The iteratee invoked per property.
 * @returns {Record<string, TValue>} Returns the new mapped object.
 * @example
 *
 * mapKeys({ a: 1, b: 2 }, (_value, key) => `${key}_x`)
 * // => { a_x: 1, b_x: 2 }
 */
export function mapKeys<TValue>(
	object: Record<string, TValue> | null | undefined,
	iteratee?: Iteratee<TValue, unknown>,
): Record<string, TValue> {
	if (object == null) {
		return {};
	}
	const source = Object(object) as Record<string, TValue>;
	const runner = toIterateeCore<TValue, unknown>(
		(iteratee ?? identity) as Iteratee<TValue, unknown>,
	);
	const result: Record<string, TValue> = {};
	for (const key of Object.keys(source)) {
		result[String(runner(source[key], key, source))] = source[key];
	}
	return result;
}

export default mapKeys;
