import { toIterateeCore } from "./internal/iteratee-core.js";
import type { Iteratee } from "./types.js";

const identity = <TValue>(value: TValue): TValue => value;

/**
 * Creates an object with the same keys as `object` and values generated by running each own
 * enumerable property value through `iteratee`.
 *
 * @since +0.1.0
 * @category Object
 * @param {Record<string, TValue> | null | undefined} object The object to iterate over.
 * @param {Iteratee<TValue, TResult>} [iteratee] The iteratee invoked per property.
 * @returns {Record<string, TResult>} Returns the new mapped object.
 * @example
 *
 * mapValues({ a: 1, b: 2 }, (value) => value * 2)
 * // => { a: 2, b: 4 }
 */
export function mapValues<TValue, TResult = TValue>(
	object: Record<string, TValue> | null | undefined,
	iteratee?: Iteratee<TValue, TResult>,
): Record<string, TResult> {
	if (object == null) {
		return {};
	}
	const source = Object(object) as Record<string, TValue>;
	const runner = toIterateeCore<TValue, TResult>(
		(iteratee ?? identity) as Iteratee<TValue, TResult>,
	);
	const result: Record<string, TResult> = {};
	for (const key of Object.keys(source)) {
		result[key] = runner(source[key], key, source);
	}
	return result;
}

export default mapValues;
