name: Unit Test (macOS)

on:
  pull_request:
    branches: [main]  # Only triggers for PRs targeting 'main' branch
on:
  push:
    branches:
      - main

jobs:
  ut-mac:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [18.x]
        os: [macos-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 25

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build
